DJANGOPROJ/LOCALLIBRARY/catalog/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from .views import index, BookListView, BookDetailView, AuthorListView, AuthorDetailView
from .views import borrowed, LoanedBooksByUserListView, renew_book_librarian
from .views import AuthorCreate, AuthorUpdate, AuthorDelete
from .views import BookCreate, BookUpdate, BookDelete

urlpatterns = [
    path('', index, name='index'),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),

    path('books/', BookListView.as_view(), name='books'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    # re_path(r'^book/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),
    path('book/create/', BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', BookDelete.as_view(), name='book-delete'),
    path('mybooks/', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', borrowed, name='borrowed'),
    path('book/<uuid:pk>/renew/', renew_book_librarian,
         name='renew-book-librarian'),

    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author-detail'),
    # re_path(r'^author/(?P<pk>\d+)$, AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJANGOPROJ/LOCALLIBRARY/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

DJANGOPROJ/LOCALLIBRARY/catalog/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
import uuid  # Required for unique book instances


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        # Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    '''
    class Meta:
            ordering = ['last_name', 'first_name']

    '''

DJANGOPROJ/LOCALLIBRARY/catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import BookInstance


class RenewBookModelForm(ModelForm):

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _(
            'Enter a date between now and 4 weeks (default 3).')}


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

DJANGOPROJ/LOCALLIBRARY/catalog/views.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseRedirect, Http404

from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import RenewBookForm
from .models import Book, Author, BookInstance, Genre

#  path('', index, name='index')


def index(request):
    num_authors = Author.objects.count()
    num_books = Book.objects.all().count()
    num_bookinstances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_bookinstances": num_bookinstances,
        'num_instances_available': num_instances_available,
        "num_authors": num_authors,
        'num_visits': num_visits
    }
    return render(request, 'catalog/index.html', context)


class MyView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'


@ login_required
@ permission_required('catalog.can_mark_returned', raise_exception=True)
def my_view(request):
    return HttpResponse('inside views.my-view')


class MyView(PermissionRequiredMixin, View):
    permission_required = 'catalog.can_mark_returned'
    # Or multiple permissions
    # , 'catalog.can_edit')
    permission_required = ('catalog.can_mark_returned')
    # Note that 'catalog.can_edit' is just an example
    # the catalog application doesn't have such permission!

# path('books/', BookListView.as_view(), name='books'),


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    print('inside views.BookListView')
    # num_authors = Author.objects.count()
    num_books = Book.objects.all().count()
    print('num_books ', num_books)
    context_object_name = 'book_list'
    print('book_list is ', context_object_name)
    # queryset = Book.objects.filter(title__icontains='Title5')[
    #    :5]  # Get 5 books containing the title war
    template_name = 'catalog/book_list.html'

# path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
# re_path(r'^book/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404('Book does not exist')

        return render(request, 'catalog/book_detail.html', context={'book': book})

    '''
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context
    '''
    '''
    def get_queryset(self):

        queryset = Book.objects.filter(title__icontains='Title4')[:5]

        # Get 5 books containing the title war
        return queryset
    '''

#   path('borrowed/', borrowed, name='borrowed'),


def borrowed(request):
    bookinstance_list = BookInstance.objects.filter(status__exact='o')
    context = {
        'bookinstance_list': bookinstance_list
    }
    return render(request, 'catalog/borrowed.html', context)


# path('mybooks/', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )

#  path('book/<uuid:pk>/renew/', renew_book_librarian,
#  name='renew-book-librarian'),


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):

    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':   # If this is a POST request then process the Form data

        # Create form instance - populate it with data from the request (binding):
        form = RenewBookForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('borrowed'))

    else:  # If this is a GET (or any other method) create the default form.
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

# path('authors/', AuthorListView.as_view(), name='authors'),


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    # num_authors = Author.objects.count()
    num_authors = Author.objects.all().count()
    context_object_name = 'author_list'
    # queryset = Author.objects.filter(title__icontains='????')[
    #    :5]  # Get 5 authors containing the title war
    template_name = 'catalog/author_list.html'

# path('author/<int:pk>', AuthorDetailView.as_view(), name='author-detail'),
# re_path(r'^author/(?P<pk>\d+)$, AuthorDetailView.as_view(), name='author-detail'),


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(request, primary_key):
        try:
            author = Author.objects.get(pk=primary_key)
        except Author.DoesNotExist:
            raise Http404('Author does not exist')

        return render(request, 'catalog/author_detail.html', context={'author': author})
        # return HttpResponse('from inside author_detail_view')

# path('author/create/', AuthorCreate.as_view(), name='author-create'),


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}

#  path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),


class AuthorUpdate(UpdateView):
    model = Author
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'

# path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


# path('author/create/', AuthorCreate.as_view(), name='author-create'),

class BookCreate(CreateView):
    print('ln 191 inside views.UserCreate')
    model = Book
    fields = '__all__'

# path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),


class BookUpdate(UpdateView):
    model = Book
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'

# path('author/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

DJANGOPROJ/LOCALLIBRARY/templates/catalog/author_confirm_delete.html
{% extends "./base_generic.html" %}

{% block contentauthor_confirm_delete %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/author_detail.html
{% extends "./base_generic.html" %}

{% block contentauthor_detail %}
  <h1>from author_detail.html</h1>
  <h1>Author: {{ book.author }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>First Name:</strong> {{ author.first_name }}</p>
  <p><strong>Last Name:</strong> {{ author.last_name }}</p>
  <p><strong>DOB:</strong> {{ author.date_of_birth }}</p>
  <p><strong>DIED:</strong> {{ author.date_of_death }}</p>
 
{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/author_form.html
{% extends "./base_generic.html" %}

{% block contentauthor_form %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/author_list.html
{% extends './base_generic.html' %}
{% block contentauthor_list %}

<div> {{some_data}} </div>

    <h1>Author List</h1>
  
    {% if author_list %}
    <p> author_list available </p>
      <ul>
       
        {% for author in author_list %}
       
        <li>
         
          
            <a href="{{ book.author.get_absolute_url }}"> {{ author.first_name }}</a>
          
          
        </li>       
        
        {% empty %}
         <p> There is no author </p>
        {% endfor %}
    
    </ul>
    {% else %}
      <p>There is no author_list </p>
    {% endif %}  


    {% endblock %}
    

DJANGOPROJ/LOCALLIBRARY/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <img
    src="{% static 'images/img1.jpeg' %}"
    alt="img1"
    style="width:555px;height:540px;" />   
   
  </head>
  <body>
    <div class="container-fluid">    
       
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'books' %}">All books</a></li>
                <li><a href="{% url 'authors' %}">All authors</a></li>
              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                <li><a href="{% url 'borrowed' %}">Borrowed</a></li>                
                <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
              {% endif %}            
            </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block contentindex %}{% endblock %}
                
                {% block contentauthor_confirm_delete %}{% endblock %}
                {% block contentauthor_detail %}{% endblock %}
                {% block contentauthor_form %}{% endblock %}
                {% block contentauthor_list %}{% endblock %}
                
                {% block contentbook_confirm_delete %}{% endblock %}
                {% block contentbook_detail %}{% endblock %}
                {% block contentbook_form %}{% endblock %}
                {% block contentbook_list %}{% endblock %}
                {% block contentbook_renew_librrian %}{% endblock %}
                {% block contentbookinstance_list_borrowed_user %}{% endblock %}
                {% block contentborrowed %}{% endblock %}
                 
                {% block contentlogin %}{% endblock %}
                {% block contentlogged_out %}{% endblock %}
                {% block contentpassword_reset_form %}{% endblock %}
                {% block contentpassword_reset_done %}{% endblock %}
                {% block contentpassword_reset_email %}{% endblock %}
                {% block contentpassword_reset_confirm %}{% endblock %}
                {% block contentpassword_reset_complete %}{% endblock %}
                
    {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}
           
            </div>     
        </div>
    </div>
  </body>
</html>

DJANGOPROJ/LOCALLIBRARY/templates/catalog/book_confirm_delete.html
{% extends "./base_generic.html" %}

{% block contentbook_confirm_delete %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/book_detail.html
{% extends "./base_generic.html" %}

{% block contentbook_detail %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/book_form.html
{% extends "./base_generic.html" %}

{% block contentbook_form %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/book_list.html
{% extends './base_generic.html' %}
{% block contentbook_list %}

<div> {{some_data}} </div>

    <h1>Book List</h1>
    {% if book_list %}
    <p> book_list available </p>
      <ul>
       
        {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}"> Title {{ book.title }}</a>
        
        </li>
        {% empty %}
         <p> There is no book </p>
        {% endfor %}
    
    </ul>
    {% else %}
      <p>There is no book_list </p>
    {% endif %}  


    {% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/book_renew_librarian.html
{% extends "./base_generic.html" %}

{% block contentbook_renew_librrian %}

  <h1>Renew:  {{ book_instance.book.title }} </h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
<!---
<tr>
    <th><label for="id_renewal_date">Renewal date:</label></th>
    <td>
      <ul class="errorlist">
        <li>Invalid date - renewal in past</li>
      </ul>
      <input id="id_renewal_date" name="renewal_date"
        type="text" value="2015-11-08" required />
      <br />
      <span class="helptext"> Enter date betn now and 4 weeks (default 3 weeks) </span>
    </td>
</tr>
-->

{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "./base_generic.html" %}

{% block contentbookinstance_list_borrowed_user %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>
     
      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}
<!---
 {% if perms.catalog.can_mark_returned %}
       <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>       
      {% endif %}
-->

DJANGOPROJ/LOCALLIBRARY/templates/catalog/borrowed.html
{% extends "./base_generic.html" %}
{% block contentborrowed %}
    <h1>All Borrowed Books</h1>
    {% if user.is_staff %}

      {% if bookinstance_list %}
    
        <h2> bookinstance_list available </h2>
        <ul>     
          {% for bookinst in bookinstance_list %}
          <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
            ({{ bookinst.due_back }}) -  ({{ bookinst.borrower }}) 
            {% if perms.catalog.can_mark_returned %}- 
            <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
            {% endif %}
          </li>
          {% endfor %}
        </ul>

      {% else %}
        <p>There are no books borrowed.</p>
      {% endif %}
    {% else %}
        <p> User is not staff, request declined </p>
    {% endif %}
{% endblock %}

DJANGOPROJ/LOCALLIBRARY/templates/catalog/index.html
{% extends './base_generic.html' %}
{% block contentindex %}
<h1>Local Library Home</h1>
  <p>
    Welcome to LocalLibrary, a website developed by
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Num_visits:</strong>{{num_visits}}</li>
  </ul>
  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}